name = "alicesaidhi/obedience"
version = "0.1.0"
description = "Modern command library for Roblox"
authors = ["alicesaidhi"]
repository = "https://github.com/alicesaidhi/obedience"
license = "MIT"

workspace_members = ["pkgs/*"]

[target]
environment = "roblox"

[scripts]
roblox_sync_config_generator = ".pesde/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/sourcemap_generator.luau"

[indices]
default = "https://github.com/daimond113/pesde-index"
